### ISSUE TITLE
always generate German and French files

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#3]
Please always generate German and French files for 
1. dhcp_hcp_de.json
2. chargenrueckrufe_de.json

French Files should be:

3. dhcp_hcp_fr.json
4. chargenrueckrufe_fr.json

**Comment by hamzamu** [comment]
Added French files

**Comment by zdavatz** [comment]
This file is still empty: http://pillbox.oddb.org/dhcp_hcp_fr.json
