### ISSUE TITLE
create JSON Web-Output

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#33]
The files are created with "meteor --once --settings swiss.json"

the URL `public/exports` no longer works.

Create JSON Web-Output for
`chargenrueckrufe_de.json`, `chargenrueckrufe_fr.json`
and
`dhcp_hcp_de.json`, `dhcp_hcp_fr.json`

The URL for each JSON file has to be unique.

The Browser has to display the JSON file.

**Comment by hamzamu** [comment]
You can access the files simply thru:

http://localhost:3000/exports/chargenrueckrufe_de.json
