### ISSUE TITLE
parse all information from pharmnet

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#4]
i.e. search for "ACC"

1. Fachinformation (Date, File and Link to File, all Versions)
2. Gebrauchsinformation (Date, File and Link to File, all Versions)
3. Eingangsnummer
4. Arzneimittelname
5. Darreichungsform
6. Antragsteller
7. Verkehrsfähig
8. Zulassungs-/Reg-Nr.(AMG76)
9. ASK-Nr
10. Stoffname
11. Stoffmenge

Create a JSON file for each product.

**Comment by zdavatz** [comment]
![Bildschirmfoto 2019-09-16 um 07 30 19](https://user-images.githubusercontent.com/4953/64935990-14d70880-d854-11e9-910e-5d93b03957ac.png)

**Comment by hamzamu** [comment]
![search-results-drug-tab](https://user-images.githubusercontent.com/340579/65019089-32c76a80-d933-11e9-8812-e1236b5bd692.png)

**Comment by zdavatz** [comment]
Use as input file for a first run.
[prodname_unique.txt](https://github.com/zdavatz/ymeteor/files/3630487/prodname_unique.txt)
