### ISSUE TITLE
make URL out of search term and set anchor

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#43]
make a URL out of the search term and create an anchor for every item, i.e.

If you search for `N02BA51` an hit enter the URL will show: "http://localhost:3000/N02BA51".

The URL `http://localhost:3000/N02BA51#4` will jump to item 4 in the list.

**Comment by zdavatz** [comment]
The goal of this is to be able to send out search links and make the page more indexable.

**Comment by zdavatz** [comment]
using https://github.com/kadirahq/flow-router according to https://guide.meteor.com/routing.html

**Comment by hamzamu** [comment]
- [*] 1- niceURL 
- [ ] 2- anchor 
- [ ] 3- forward + backward buttons

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/73558212-04b27500-4453-11ea-9e10-d4eb8198e43d.png)
