### ISSUE TITLE
Chargenrückrufe Humanarzneimittel and DHPC/HPC – (Direct) Healthcare Professional Communications are not updated

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ymeteor#52]
`meteor --once --settings swissmedic.json` does not grab the latest data for Chargenrückrufe Humanarzneimittel and DHPC/HPC – (Direct) Healthcare Professional Communications.

DHCP Entries are only parsed up to 16.1.2020.
https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/health-professional-communication--hpc-.html

Chargenrückrufe are only parsed up to 17.1.2020
https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/qualitaetsmaengel-und-chargenrueckrufe/chargenrueckrufe.html

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/94237496-4080da00-ff0f-11ea-9438-9a2e4d8e53b5.png)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/94237565-5c847b80-ff0f-11ea-83c7-e8af2c80df6e.png)

**Comment by hamzamu** [comment]
![Screenshot from 2020-09-25 11-19-50](https://user-images.githubusercontent.com/340579/94244322-5dbea400-ff21-11ea-99c4-984d353b0fc3.png)

**Comment by hamzamu** [comment]
![Screenshot from 2020-09-25 11-23-14](https://user-images.githubusercontent.com/340579/94244421-85157100-ff21-11ea-9864-68eb99cf4b50.png)

**Comment by zdavatz** [comment]
What version of Meteor are you using?

**Comment by zdavatz** [comment]
Now it seems to be working for me as well.

**Comment by zdavatz** [comment]
This date also is strange.
![latest-screenshot](https://user-images.githubusercontent.com/4953/94245344-6495e880-ff1a-11ea-84c6-240ee1944601.png)

**Comment by hamzamu** [comment]
Meteor version 
METEOR@1.8.3

**Comment by zdavatz** [comment]
cat .meteor/release shows me `METEOR@1.11.1`

**Comment by zdavatz** [comment]
They are updated, but they are not sorted. See #53
